Squashed 'grapesjs/' changes from 01254dc21..4cfc3d5ad
4cfc3d5ad Merge pull request #1045 from artf/dev
84c2db2a9 Merge branch 'master' into dev
8750bc63a Bump v0.14.9
f6778b956 Prevent `null` contRules in CssRulesView
6d1527abc Merge branch 'dev' of https://github.com/artf/grapesjs into dev
834cebf27 Merge pull request #1040 from dsgh/support-no-name-traits Fixes #1039
54be98bad Add `label` property to buttons. Closes #1031
17e90f9f4 Clean ButtonView form useless code
c1bffbdef Fix CSS rule rendering with custom media rules
210627ba2 Support no-name traits
b62e032b0 Merge branch 'dev' of https://github.com/artf/grapesjs into dev
79d6aafca Merge pull request #1038 from dsgh/fix-percent-media-width Fixes #1037
29aa0aec4 Merge pull request #1036 from tommedema/dev-fonts
f3f3bb4a6 Rename option `removeEmptyTextNodes` -> `keepEmptyTextNodes`
43d5e07ac Merge pull request #1035 from dsgh/yarn-ignore
4fdc7dfd9 Less strict on boolean types
8b417ae51 Merge branch 'dev' of https://github.com/artf/grapesjs into dev
5b3f01e69 Merge pull request #1023 from tommedema/master Fixes #989
87d752e47 Add more storage events `storage:start:store`, `storage:start:load`, `storage:end:store`, `storage:end:load`
e728eb8c6 allow for multiple at-rules
767e0673a Support percentage based media-widths
d5b1c51e3 Ignore yarn files so contributors can use it
2c8b06728 added test cases for multiple font faces
6147e1bbb Merge branch 'dev' of https://github.com/artf/grapesjs into dev
cfde1c141 Merge pull request #988 from vrudikov/972-added-style-containers Fixes #896
bb952eaac Get mediaCondition from Editor model config. Fixed tests - add storable to Editor model, proper CssComposer init
cd5fdbf72 Merge pull request #1017 from artf/revert-1010-master
f823b5e9e Revert "implemented removeEmptyTextNodes boolean, fixes #989"
28c9fe715 Merge pull request #1010 from tommedema/master
16e026c49 Add `avoidDefaults` option
4e8c1c059 Add `storage:store:before` event
4d72da01c Fixed tests - replaced getElementById with querySelector to avoid "getElementById is not a function" error
b4e9a024d Applied fixes and improvements based on PR comments
634cad4e0 Merge branch 'dev' of https://github.com/artf/grapesjs into 972-added-style-containers
00d97955a negative strict equality check because config is not always available in test suite
935ad309c implemented removeEmptyTextNodes boolean (defaults to true to prevent breaking changes); fixes #989
426c5efe5 Listen traits change on components
d0023f955 Cache the return of `getClearEl`. Fixes #768
e0b775326 Add a monkey patch for the cash's `removeClass` to make it work with IE #768
94eba6b89 Fix `append` method in JsContainer
1141f6789 Merge branch 'dev' of https://github.com/artf/grapesjs into dev
d89f9844c Merge pull request #983 from funkjedi/funkjedi-patch-1
3775f8fa2 Fix loading with autoload but without the storage
56addf73c Removed unused require
1280f7c8a Fixed tests
5d0e9567a Don't stringify `script`s function in toJSON method. Fixes #980
8d29d2001 Check if loaded CSS is actually empty
033ed7d0c Avoid adding CssRules with empty style object
38a0dc843 Added style containers to fix styles/media-query order
2e8a0429d Update storage:load event
ffa06de3d Make font size variables overridable
396047a9e Add `core:component-delete` command
98896c0e8 Add new Command lifecycle events
ec4173b7f Merge branch 'dev' of https://github.com/artf/grapesjs into dev
d5f0ae94d Merge pull request #942 from tommedema/wip-pr-expose-base-css
4b565fe31 Remove controls option for Vimeo videos as it's only for PRO users. Closes #977
7af53cd5a Merge pull request #971 from chapterjason/patch-1
bee57c85f Fix youtube loop parameter in Video Component. Fixes #969
20c0177d3 keep readme clean
3ea720c93 Check if the event exists in move command. Fixes #710
d27819c3e Fix some issues in IE11 #768
ac15b233c Updated block_manager config.js
376a60867 Merge pull request #961 from artf/dev
1efe55fcf Bump v0.14.6
7621704f8 Fix the import of components and styles with the same ids. Fixes #932
e6593e7ad Fix block text overflow. Closes #946
3646d9fc4 removed redudandant options and global
aba4b2362 enabled iframes in jsdoc and added positive and negative tests for baseCss overwriting feature
7619979da Once the id rule is created in Component, clean its internal style
9a71368f4 Manage correctly boolean attributes in HTML output. Fixes #943
b20dd6f4b Check if the attribute is a string before replacing
64a8fafbe Merge branch 'dev' of https://github.com/artf/grapesjs into dev
a36ddc99f Merge pull request #939 from ryandeba/escape-attributes
0e47b6fe5 revert previous test change
61ef0fba5 wip test case
6d095a031 add baseCss overwrite documentation
cf431db23 use config.baseCss in canvasView if set in config
ff15c3454 escpae quotes in Component.toHTML
87bff5d1d Refactor OpenTraitManager
e6395e23a Merge pull request #929 from ryandeba/trait-manager-no-comp-msg Closes #869
a724b6698 Merge pull request #928 from tommedema/no-duplicate-dev-js
baf578dcf Refactor few methods in Canvas
799e4e030 Merge branch 'dev' of https://github.com/artf/grapesjs into dev
1e3dc7124 Merge pull request #920 from nojacko/dev Fixes #914
48a3bccb2 modify Component.toHTML to property encode attribute values
0a11ea864 add failing unit test
d1af24d84 show message in trait manager panel when there is no comp selected
cc029b774 prevent grapes.js from being injected twice during development
3e89fe14c Fixed TypeError when canvas has been removed.
c77308558 Merge branch 'dev' of https://github.com/artf/grapesjs into dev
49100b2f6 Merge pull request #881 from maxtacco/dev Closes #876
feb9a8b67 Init correctly components with javascript. Fixes #873
e60a5bcda Escape title inside blocks
dab30fd8f Pass response to 'editor.store(clb)' callback. Closes #876
1f2a083ca Merge branch 'dev' of https://github.com/artf/grapesjs into dev
4079db906 Merge pull request #870 from JuanTincho/Large-block-label
1fe03ddce Don't trigger `component:add` when components are just moved. Fixes #868
c23c9519c  * Added css to hide very large labels.  * Added title to label class, thus it shows the text on a tooltip.

git-subtree-dir: grapesjs
git-subtree-split: 4cfc3d5ad88f688e5438977909cf7c61031cffaf